# Generated by Django 3.1.5 on 2021-02-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес кафе'),
        ),
    ]
