# Generated by Django 3.1.5 on 2021-02-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_city_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='coordinates',
            field=models.CharField(max_length=255, null=True, verbose_name='Координаты'),
        ),
    ]
