# Generated by Django 3.1.5 on 2021-03-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210225_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=100, verbose_name='Номер по порядку')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать баннер?')),
                ('is_main', models.BooleanField(default=False, verbose_name='Это город по умолчанию?')),
            ],
            options={
                'verbose_name': 'Баннеры',
                'verbose_name_plural': 'Баннер',
            },
        ),
    ]
