# Generated by Django 3.1.5 on 2021-03-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_banners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ('-order_num',), 'verbose_name': 'Баннеры', 'verbose_name_plural': 'Баннер'},
        ),
        migrations.RemoveField(
            model_name='banners',
            name='is_main',
        ),
    ]
