# Generated by Django 3.1.5 on 2021-03-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210304_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='belki',
            field=models.IntegerField(default=0, verbose_name='Белки'),
        ),
        migrations.AddField(
            model_name='item',
            name='callories',
            field=models.IntegerField(default=0, verbose_name='Калорий'),
        ),
        migrations.AddField(
            model_name='item',
            name='fat',
            field=models.IntegerField(default=0, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='item',
            name='uglevod',
            field=models.IntegerField(default=0, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='price_33',
            field=models.IntegerField(default=0, verbose_name='Цена для пиццы 33см'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес (для пиццы это вес 28см)'),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена (если пицца то для размера 28см)'),
        ),
    ]
