# Generated by Django 3.1.5 on 2021-03-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20210312_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight_33',
            field=models.IntegerField(default=0, verbose_name='Вес для пиццы 33см)'),
        ),
    ]
