# Generated by Django 3.1.5 on 2021-03-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_weight_33'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_num',
            field=models.IntegerField(default=100, verbose_name='Порядок вывода'),
        ),
    ]
