# Generated by Django 3.1.5 on 2021-03-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_category_order_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseingridient',
            options={'ordering': ('name',), 'verbose_name': 'Базовый ингридиент', 'verbose_name_plural': 'Базовые ингридиенты'},
        ),
        migrations.AddField(
            model_name='item',
            name='order_num',
            field=models.IntegerField(default=100),
        ),
    ]
