# Generated by Django 3.1.5 on 2021-04-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20210325_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order_num',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('order_num',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
