# Generated by Django 3.1.5 on 2021-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20210403_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_gift',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Товар подарок ?'),
        ),
    ]
