# Generated by Django 3.1.5 on 2021-04-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_itemprice_is_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprice',
            name='is_discount',
        ),
        migrations.AddField(
            model_name='itemprice',
            name='old_price',
            field=models.IntegerField(default=0),
        ),
    ]
