# Generated by Django 3.1.5 on 2021-04-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20210407_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Отображать ?'),
        ),
    ]
