# Generated by Django 3.1.5 on 2021-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_item_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='city',
            field=models.ManyToManyField(blank=True, db_index=True, to='items.City', verbose_name='Категория доступна в городах'),
        ),
    ]
