# Generated by Django 3.1.5 on 2021-04-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_category_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='old_price_33',
            field=models.IntegerField(default=0),
        ),
    ]
