# Generated by Django 3.1.5 on 2021-07-11 09:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_remove_item_is_show_at_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeaddress',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='city',
            name='about_image',
            field=models.ImageField(blank=True, upload_to='city/', verbose_name='Главное изображение на странице о нас'),
        ),
        migrations.AddField(
            model_name='city',
            name='about_kitchen',
            field=models.ImageField(blank=True, upload_to='city/', verbose_name='Изображение кухни на странице о нас'),
        ),
        migrations.AddField(
            model_name='city',
            name='about_p9_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст пункта 9'),
        ),
        migrations.AddField(
            model_name='city',
            name='contacts_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Тект для вкладки Детали'),
        ),
        migrations.AddField(
            model_name='city',
            name='delivery_from_price',
            field=models.CharField(max_length=255, null=True, verbose_name='СУММА ЗАКАЗА'),
        ),
        migrations.AddField(
            model_name='city',
            name='delivery_price',
            field=models.CharField(max_length=255, null=True, verbose_name='ЦЕНА ДОСТАВКИ'),
        ),
        migrations.AddField(
            model_name='city',
            name='delivery_time',
            field=models.CharField(max_length=255, null=True, verbose_name='ВРЕМЯ ДОСТАВКИ'),
        ),
        migrations.AddField(
            model_name='city',
            name='delivery_times',
            field=models.CharField(max_length=255, null=True, verbose_name='ДОСТАВКА РАБОТАЕТ'),
        ),
        migrations.AddField(
            model_name='city',
            name='domain',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Домен'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_show_peoples',
            field=models.BooleanField(default=False, verbose_name='Отображать поваров'),
        ),
        migrations.AddField(
            model_name='city',
            name='main_phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон в шапке'),
        ),
        migrations.AddField(
            model_name='city',
            name='order_email',
            field=models.CharField(max_length=255, null=True, verbose_name='Email для отправки заказа'),
        ),
        migrations.AddField(
            model_name='city',
            name='order_phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон для отправки заказа'),
        ),
        migrations.AddField(
            model_name='city',
            name='payment_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Тект для вкладки Детали'),
        ),
        migrations.AddField(
            model_name='city',
            name='sber_login',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Логин сбре'),
        ),
        migrations.AddField(
            model_name='city',
            name='sber_pass',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Пароль сбер'),
        ),
    ]
