# Generated by Django 3.1.5 on 2021-07-13 07:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_auto_20210711_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='inst_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='city',
            name='policy_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Тект политики'),
        ),
        migrations.AddField(
            model_name='city',
            name='rules_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Тект правил'),
        ),
        migrations.AddField(
            model_name='city',
            name='vk_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vk'),
        ),
    ]
