# Generated by Django 3.1.5 on 2021-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20210713_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sber_url',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Пароль URL'),
        ),
    ]
