# Generated by Django 3.1.5 on 2021-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_auto_20210726_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='call_tracker_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='metrika_id',
            field=models.IntegerField(default=0),
        ),
    ]
