# Generated by Django 3.1.5 on 2021-07-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_auto_20210729_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='call_tracker_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Calltrack'),
        ),
        migrations.AlterField(
            model_name='city',
            name='metrika_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Metrika'),
        ),
    ]
