# Generated by Django 3.1.5 on 2021-09-16 12:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_auto_20210729_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='modalText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Тект модалки'),
        ),
    ]
