# Generated by Django 3.1.5 on 2021-11-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_city_modaltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeaddress',
            name='order_email',
            field=models.CharField(max_length=255, null=True, verbose_name='Email для отправки заказа'),
        ),
    ]
