# Generated by Django 4.2.1 on 2023-12-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0030_cafeaddress_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='shopID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
