# Generated by Django 5.0.1 on 2024-01-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0032_city_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='delivery_price',
            field=models.IntegerField(max_length=255, null=True, verbose_name='ЦЕНА ДОСТАВКИ'),
        ),
    ]
