# Generated by Django 5.0.1 on 2024-01-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0033_alter_city_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='delivery_price',
            field=models.IntegerField(default=150, max_length=255, verbose_name='ЦЕНА ДОСТАВКИ'),
        ),
    ]
