# Generated by Django 5.0.1 on 2024-01-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_alter_city_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='tg_chat_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
