# Generated by Django 5.0.1 on 2024-06-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_city_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='use_doogly',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DooglyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doogly_id', models.CharField(max_length=255, null=True, verbose_name='ID Doogly')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.city', verbose_name='Город')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Связь товара с ID Doogly',
                'verbose_name_plural': 'Связи товаров с ID Doogly',
            },
        ),
    ]
