# Generated by Django 5.2.7 on 2026-01-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0036_city_use_doogly_dooglyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='online_payment_active',
            field=models.BooleanField(default=True),
        ),
    ]
