# Generated by Django 3.1.5 on 2021-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=100, verbose_name='Порядок вывода')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название акции')),
                ('image', models.ImageField(blank=True, upload_to='promotions/', verbose_name='Изображение')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=False, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ('order_num',),
            },
        ),
    ]
