# Generated by Django 3.1.5 on 2021-07-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20210711_1213'),
        ('promotion', '0002_promotion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.city', verbose_name='Город'),
        ),
    ]
