# Generated by Django 3.1.5 on 2021-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_auto_20210726_1859'),
        ('promotion', '0004_promotion_is_need_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='cart_summ',
            field=models.IntegerField(default=0, verbose_name='Сумма корзины чтобы активировалась скидка'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка в корзине'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='items',
            field=models.ManyToManyField(blank=True, to='items.Item'),
        ),
    ]
