# Generated by Django 3.1.5 on 2021-02-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0)),
                ('total_bonuses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True, unique=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Кол-во')),
                ('price_per_unit', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('bonuses', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Конструктор в корзине',
                'verbose_name_plural': 'Конструкторы в корзинах',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True, unique=True)),
                ('selected_size', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('units', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Кол-во')),
                ('ingridients_price', models.IntegerField(default=0)),
                ('price_per_unit', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('bonuses', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзинах',
            },
        ),
        migrations.CreateModel(
            name='CartItemAdditionalIngrigient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_added', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItemBaseIngrigient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartSouce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True, unique=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Кол-во')),
                ('price_per_unit', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('bonuses', models.IntegerField(default=0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.city')),
            ],
            options={
                'verbose_name': 'Соус в корзине',
                'verbose_name_plural': 'Соусы в корзинах',
            },
        ),
    ]
