# Generated by Django 3.1.5 on 2021-02-10 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsouce',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartsouce',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.guest'),
        ),
        migrations.AddField(
            model_name='cartsouce',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.souce'),
        ),
        migrations.AddField(
            model_name='cartitembaseingrigient',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.baseingridient'),
        ),
        migrations.AddField(
            model_name='cartitemadditionalingrigient',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.additionalingridient'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='additional_ingridients',
            field=models.ManyToManyField(blank=True, to='cart.CartItemAdditionalIngrigient', verbose_name='Дополнительные ингридиенты'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='base_ingridients',
            field=models.ManyToManyField(blank=True, to='cart.CartItemBaseIngrigient', verbose_name='Базовые ингридиенты'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.city'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.guest'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='cartconstructor',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.city'),
        ),
        migrations.AddField(
            model_name='cartconstructor',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartconstructor',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.guest'),
        ),
        migrations.AddField(
            model_name='cartconstructor',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='items.Item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Корзина клиента'),
        ),
        migrations.AddField(
            model_name='cart',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.guest', verbose_name='Корзина гостя'),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='cart.CartItem', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pizza_constructors',
            field=models.ManyToManyField(blank=True, to='cart.CartConstructor', verbose_name='Собранные пиццы'),
        ),
        migrations.AddField(
            model_name='cart',
            name='souces',
            field=models.ManyToManyField(blank=True, to='cart.CartSouce', verbose_name='Соусы'),
        ),
    ]
