# Generated by Django 3.1.5 on 2021-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210210_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='persons',
            field=models.IntegerField(default=1),
        ),
    ]
