# Generated by Django 3.1.5 on 2021-07-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_apply_promo',
            field=models.BooleanField(default=False),
        ),
    ]
