# Generated by Django 3.1.5 on 2021-08-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_auto_20210729_2033'),
        ('courier', '0002_auto_20210826_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.city'),
        ),
    ]
