# Generated by Django 3.1.5 on 2021-08-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_courier_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courierorder',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='courier',
            name='have_orders_in_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courier',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон (формат номера 79991112233)'),
        ),
    ]
