# Generated by Django 3.1.5 on 2021-08-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_auto_20210831_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierorder',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='courier',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
