# Generated by Django 3.1.5 on 2021-02-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='bonuses',
            field=models.IntegerField(default=0),
        ),
    ]
