# Generated by Django 3.1.5 on 2021-02-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_guest_bonuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='bonuses',
        ),
        migrations.AddField(
            model_name='user',
            name='bonuses',
            field=models.IntegerField(default=0),
        ),
    ]
