# Generated by Django 3.1.5 on 2021-02-10 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.promo'),
        ),
    ]
