# Generated by Django 3.1.5 on 2021-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ip'),
        ),
    ]
