# Generated by Django 5.0.1 on 2024-09-24 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='is_only_for_registered',
            field=models.BooleanField(default=False, verbose_name='Только для зареганных'),
        ),
        migrations.CreateModel(
            name='PromoUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.promo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
