# Generated by Django 3.1.5 on 2021-02-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
