# Generated by Django 3.1.5 on 2021-02-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
