# Generated by Django 3.1.5 on 2021-03-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cafe_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
