# Generated by Django 3.1.5 on 2021-03-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_cafe_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cashback',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
