# Generated by Django 3.1.5 on 2021-07-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20210713_1051'),
        ('order', '0008_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.city'),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
