# Generated by Django 3.1.5 on 2021-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210713_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_apply_promo',
            field=models.BooleanField(default=False),
        ),
    ]
