# Generated by Django 3.1.5 on 2021-08-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210825_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_assing',
            field=models.BooleanField(default=False),
        ),
    ]
