# Generated by Django 3.1.5 on 2021-09-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210914_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='is_payed',
        ),
        migrations.AddField(
            model_name='order',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
