# Generated by Django 3.1.5 on 2023-04-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
