# Generated by Django 5.0.1 on 2024-01-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_phone_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/order/'),
        ),
    ]
